// test the get matches route

# @name login

POST http://127.0.0.1:4000/api/user/login
content-type: application/json; charset=utf-8

{
    "email": "ella.lewis@email.com",
    "password": "password"
}

###
@authToken = {{login.response.body.token}}
###

GET http://127.0.0.1:4000/api/user
Authorization: Bearer {{authToken}}

### 

GET http://127.0.0.1:4000/api/match
Authorization: Bearer {{authToken}}
