export const YEARS_OF_PRACTICE = [
  "< 1 year",
  "1-5 years",
  "5-10 years",
  "10-20 years",
  "20 years +",
];

export const DESIGNATION = ["NP", "RN", "LPN", "Student", "HCA", "RPN"];

export const ZONE = ["North", "South", "Central", "Edmonton", "Calgary"];

export const AREA = [
  "Orthopedics",
  "Cardiology",
  "Oncology",
  "Medicine",
  "Surgery",
  "Neurology",
  "Intensive Care",
  "Palliative Care",
  "Plastics/Burns",
  "Addiction/Mental Health",
  "Leadership",
  "Education",
  "Public Health",
  "Obstetrics",
  "Home Care",
  "Facility Living",
  "Supportive Living",
  "Emergency",
  "Specialty clinic",
  "Primary Care",
  "Pediatrics",
  "Geriatrics",
  "Transition services",
  "Connect Care",
  "Infectious Disease",
  "Workplace Safety",
  "Human Resources",
  "Health Profession Strategy and Practice",
  "Rehabilitation",
  "Nursing Informatics",
  "Pulmonary Medicine",
  "Chronic Disease Management",
  "Nephrology",
  "Hematology",
  "Pediatric ICU",
  "Health Link",
  "Public Health",
  "Operating Room",
  "Brain Injury",
  "Psychiatry",
  "Women's Health",
  "Bariatrics",
  "Other",
];

export const SKILLS_GOALS = [
  "Clinical Support",
  "Procedural Support",
  "Leadership skills",
  "Education",
  "Career goals",
  "Project Management",
  "Change Management",
  "Strategic Planning",
  "Relationship building",
  "Nursing Professional Practice",
  "Professional Growth",
  "Creative Problem Solving",
  "System Thinking",
  "Nursing Opportunities",
  "Self Care",
  "Boundary Setting",
  "Public Speaking",
  "Collaboration",
  "Inclusivity",
  "Quality Improvement",
  "Design",
  "Opportunity for Discovery",
  "Advocacy",
  "Community Resources",
  "Patient Safety",
  "Innovation",
  "Staff Safety",
  "Other",
];
